### ISSUE TITLE
import error with raspberry pi

### ISSUE THREAD

**Issue by alihanks** [sparkfun/Qwiic_KX13X_Py#5]
I am trying to use this software to interface with the sparkfun triple axis accelerometer breakout. I am using a python 3b+ with the bullseye Raspian OS and python 3.9. The error I'm getting is:

`
import qwiic_kx13x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/qwiic_kx13x.py", line 334
    """
       ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xa0 in position 173: invalid start byte
`
I have also gotten the same error using an older Raspian OS and python 3.5.

**Comment by hernandezurbina** [comment]
is this solved? I'm getting the same error on a Raspberry Pi 4 using a servo phat to connect the qwiic accelerometer. I'm using python 3.7.

**Comment by greg-jc** [comment]
Has this been solved yet? I am using the Triple Axis Accelerometer Breakout - KX132 on a Raspberry Pi 4B connected with the Sparkfun Raspberry Pi Qwiic SHIM. Raspberry Pi OS and Python version 3.9.2. It gives me the same error.

**Comment by Aser-Abdelfatah** [comment]
I'm getting same error with Nvidia Jetbot

**Comment by sfe-SparkFro** [comment]
Hi folks, sorry for the delay on this fix! I had the same problem. Looks like there was a weird character in the comment block that caused this, so I just removed that and it imports fine on my end now.

**Comment by Aser-Abdelfatah** [comment]
Now, I get a different error: Invalid driver class name. Unable to locate QwiicKx13X

**Comment by sfe-SparkFro** [comment]
Good catch! I also get this when calling `import qwiic`, as indicated by [this issue in Qwiic_Py](https://github.com/sparkfun/Qwiic_Py/issues/25). `import qwiic_kx13x` seems to work fine, so you can use that as a workaround until that gets fixed.
